version: 2

test-defaults: &test-defaults
  working_directory: ~/baikal
  steps:
    - checkout
    - run: |
        sudo -E ./ci_tools/test_job.sh

jobs:
  test-py3.5:
    <<: *test-defaults
    docker:
      - image: circleci/python:3.5.7-stretch
  test-py3.6:
    <<: *test-defaults
    docker:
      - image: circleci/python:3.6.8-stretch
  test-py3.7:
    <<: *test-defaults
    docker:
      - image: circleci/python:3.7.3-stretch
    environment:
      RUN_TEST_WITH_COVERAGE: 1

workflows:
  version: 2
  build-deploy:
    jobs:
      - test-py3.5
      - test-py3.6
      - test-py3.7
